# Default values for splunk-enterprise-local.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: splunk/splunk
  pullPolicy: IfNotPresent

podAnnotations: {}

service:
  type: NodePort
  port: 8000
  nodePort: 32767
