# Default values for splunk-enterprise-local.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: splunk/splunk
  pullPolicy: IfNotPresent

podAnnotations: {}

services:
  type: NodePort
  http:
      port: 8000
      nodePort: 32080
  hec:
      port: 8088
      nodePort: 32088
