apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "splunk-enterprise-local.fullname" . }}
  labels:
    {{- include "splunk-enterprise-local.labels" . | nindent 4 }}
data:
  splunk_start_args: "--accept-license"
