apiVersion: v1
kind: Secret
metadata:
  name: {{ include "splunk-enterprise-local.fullname" . }}
  labels:
    {{- include "splunk-enterprise-local.labels" . | nindent 4 }}
type: Opaque
stringData:
  splunk_password: "password"
